
import "./main.less";
import * as React from "react";
import * as ReactDOM from "react-dom";
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCheck, 
        faGraduationCap, 
        faCannabis, 
        faCompass,
        faChessQueen, 
        faChessKing, 
        faCarrot, faBars, 
        faPaperPlane, 
        faSpinner, 
        faTrophy, 
        faStar, 
        faTimes, 
        faKissWinkHeart, 
        faReceipt,
        faHandPaper,
        faFileSignature,
        faBullhorn,
        faPlus,
        faSignOutAlt,
        faSignInAlt,
        faMinus,
        faHome,
        faPuzzlePiece,
        faList,
        faUsers,
        faChartBar,
        faUserCog,
        faToggleOff,
        faToggleOn,
        faAngleRight,
        faAngleLeft,
        faInfo,
        faPowerOff,
        faRedo,
        faFlagCheckered,
        faShieldAlt,
        faBan,
        faDatabase,
        faPlug,
        faBinoculars,
        faUser,
        faServer} from '@fortawesome/free-solid-svg-icons';
import { App } from "./App";
// Add custom icon to Font Awesome
library.add(faCheck, 
            faGraduationCap, 
            faCannabis, 
            faCompass,
            faChessQueen, 
            faChessKing, 
            faCarrot, 
            faBars, 
            faPaperPlane, 
            faSpinner, 
            faTrophy, 
            faStar, 
            faTimes, 
            faKissWinkHeart, 
            faReceipt,
            faHandPaper,
            faHome,
            faFileSignature,
            faBullhorn,
            faPlus,
            faSignOutAlt,
            faSignInAlt,
            faMinus,
            faPuzzlePiece,
            faList,
            faUsers,
            faChartBar,
            faUserCog,
            faToggleOff,
            faToggleOn,
            faAngleRight,
            faAngleLeft,
            faInfo,
            faPowerOff,
            faRedo,
            faFlagCheckered,
            faShieldAlt,
            faDatabase,
            faPlug,
            faBinoculars,
            faBan,
            faUser,
            faServer);
// Used for webpack to load less
!!React;
// Init Socket,io
declare const io: any;
// Get Socket.io
let socket = io('/pizi-server');
ReactDOM.render(<App socket={socket}/>, document.getElementsByTagName("app")[0]);